- hosts: all
  tasks: 
  
  - name: Install vim
    import_role:
      name: ansible-role-packages
  
  - name: Inystall python3
    import_role:
      name: ansible-role-python3 
  
  - name: Git clone
    shell: 'cd /tmp && git clone https://github.com/anfederico/Flaskex'
    args:
      creates: /tmp/Flaskex 
  
  - name: install requirements
    shell: 'cd /tmp/Flaskex && pip3 install -r requirements.txt'
  
  - name: Run app
    args:
      chdir: /tmp/Flaskex
    shell: 'nohup python3 app.py &'        
  